config/routes.rb
Rails.application.routes.draw do
  resources :lifestamps
  resources :topics
  devise_for :users

end

app/models/lifestamp.rb
class Lifestamp < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lifestamps_controller.rb
class LifestampsController < ApplicationController
  before_action :set_lifestamp, only: [:show, :edit, :update, :destroy]

  # GET /lifestamps
  # GET /lifestamps.json
  def index
    @lifestamps = Lifestamp.all
  end

  # GET /lifestamps/1
  # GET /lifestamps/1.json
  def show
  end

  # GET /lifestamps/new
  def new
    @lifestamp = Lifestamp.new
  end

  # GET /lifestamps/1/edit
  def edit
  end

  # POST /lifestamps
  # POST /lifestamps.json
  def create
    @lifestamp = Lifestamp.new(lifestamp_params)

    respond_to do |format|
      if @lifestamp.save
        format.html { redirect_to @lifestamp, notice: 'Lifestamp was successfully created.' }
        format.json { render :show, status: :created, location: @lifestamp }
      else
        format.html { render :new }
        format.json { render json: @lifestamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lifestamps/1
  # PATCH/PUT /lifestamps/1.json
  def update
    respond_to do |format|
      if @lifestamp.update(lifestamp_params)
        format.html { redirect_to @lifestamp, notice: 'Lifestamp was successfully updated.' }
        format.json { render :show, status: :ok, location: @lifestamp }
      else
        format.html { render :edit }
        format.json { render json: @lifestamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lifestamps/1
  # DELETE /lifestamps/1.json
  def destroy
    @lifestamp.destroy
    respond_to do |format|
      format.html { redirect_to lifestamps_url, notice: 'Lifestamp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lifestamp
      @lifestamp = Lifestamp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lifestamp_params
      params.require(:lifestamp).permit(:value, :timestamp, :topic_id)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = current_user.topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lifestamps_helper.rb
module LifestampsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lifestamps/_form.html.erb
<%= form_for(@lifestamp) do |f| %>
  <% if @lifestamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lifestamp.errors.count, "error") %> prohibited this lifestamp from being saved:</h2>

      <ul>
      <% @lifestamp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br>
    <%= f.text_field :topic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lifestamps/edit.html.erb
<h1>Editing Lifestamp</h1>

<%= render 'form' %>

<%= link_to 'Show', @lifestamp %> |
<%= link_to 'Back', lifestamps_path %>

app/views/lifestamps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lifestamps</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Timestamp</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lifestamps.each do |lifestamp| %>
      <tr>
        <td><%= lifestamp.value %></td>
        <td><%= lifestamp.timestamp %></td>
        <td><%= lifestamp.topic %></td>
        <td><%= link_to 'Show', lifestamp %></td>
        <td><%= link_to 'Edit', edit_lifestamp_path(lifestamp) %></td>
        <td><%= link_to 'Destroy', lifestamp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lifestamp', new_lifestamp_path %>

app/views/lifestamps/new.html.erb
<h1>New Lifestamp</h1>

<%= render 'form' %>

<%= link_to 'Back', lifestamps_path %>

app/views/lifestamps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @lifestamp.value %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @lifestamp.timestamp %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @lifestamp.topic %>
</p>

<%= link_to 'Edit', edit_lifestamp_path(@lifestamp) %> |
<%= link_to 'Back', lifestamps_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.user %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @topic.user %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>